# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-04-03 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchID', models.CharField(max_length=50)),
                ('win', models.CharField(max_length=250)),
                ('time', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='hero',
            name='hName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Match'),
        ),
    ]
