# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-04-03 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='HeroName',
            field=models.CharField(default='Axe', max_length=250),
            preserve_default=False,
        ),
    ]
