# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-04-03 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_hero_heroname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='hName',
            new_name='gameID',
        ),
    ]
