# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-04-25 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20170403_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='id',
        ),
        migrations.AlterField(
            model_name='match',
            name='matchID',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
